from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
from PyQt5.QtSql import QSqlQuery

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 283)
        MainWindow.setMinimumSize(QtCore.QSize(500, 283))
        MainWindow.setMaximumSize(QtCore.QSize(500, 283))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 161, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 111, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 141, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 101, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 181, 18))
        self.label_5.setObjectName("label_5")
        self.clientFIOLine = QtWidgets.QLineEdit(self.centralwidget)
        self.clientFIOLine.setGeometry(QtCore.QRect(180, 30, 301, 24))
        self.clientFIOLine.setObjectName("clientFIOLine")
        self.clientOrdNumLine = QtWidgets.QLineEdit(self.centralwidget)
        self.clientOrdNumLine.setGeometry(QtCore.QRect(180, 70, 301, 24))
        self.clientOrdNumLine.setObjectName("clientOrdNumLine")
        self.clientTelLine = QtWidgets.QLineEdit(self.centralwidget)
        self.clientTelLine.setGeometry(QtCore.QRect(180, 110, 301, 24))
        self.clientTelLine.setObjectName("clientTelLine")
        self.clientEmailLine = QtWidgets.QLineEdit(self.centralwidget)
        self.clientEmailLine.setGeometry(QtCore.QRect(180, 150, 301, 24))
        self.clientEmailLine.setObjectName("clientEmailLine")
        self.clientOrganLine = QtWidgets.QLineEdit(self.centralwidget)
        self.clientOrganLine.setGeometry(QtCore.QRect(210, 190, 271, 24))
        self.clientOrganLine.setObjectName("clientOrganLine")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 230, 271, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveClientBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveClientBtn.setObjectName("saveClientBtn")
        self.horizontalLayout.addWidget(self.saveClientBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancelClientBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelClientBtn.setObjectName("cancelClientBtn")
        self.horizontalLayout.addWidget(self.cancelClientBtn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.cancelClientBtn.clicked.connect(MainWindow.close)
        self.saveClientBtn.clicked.connect(self.add_to_table)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Добавить клиента"))
        self.label.setText(_translate("MainWindow", "ФИО Контакт. лица"))
        self.label_2.setText(_translate("MainWindow", "Номер заказа"))
        self.label_3.setText(_translate("MainWindow", "Контакт. телефон"))
        self.label_4.setText(_translate("MainWindow", "Email адрес"))
        self.label_5.setText(_translate("MainWindow", "Название организации"))
        self.saveClientBtn.setText(_translate("MainWindow", "Сохранить"))
        self.cancelClientBtn.setText(_translate("MainWindow", "Отмена"))

    def add_to_table(self):
        con = QtSql.QSqlDatabase.addDatabase('QSQLITE')
        con.setDatabaseName('TAH.db')
        con.open()
        stm = QtSql.QSqlTableModel()
        stm.setTable('Customers')
        stm.setSort(1, QtCore.Qt.AscendingOrder)
        stm.select()
        query = QSqlQuery()

        FIOValue = self.clientFIOLine.text()
        PhoneValue = self.clientTelLine.text()
        OrdNumValue = self.clientOrdNumLine.text()
        EmailValue = self.clientEmailLine.text()
        OrganValue = self.clientOrganLine.text()

        if FIOValue != "" and PhoneValue != "" and OrdNumValue != "" and EmailValue != "" and OrganValue != "":
            query.prepare("INSERT INTO Customers(Cust_name, Cust_phone_number, Cust_email, Cust_org_name, Order_ID)"
                          "VALUES (?, ?, ?, ?, ?)")

            query.addBindValue(FIOValue)
            query.addBindValue(PhoneValue)
            query.addBindValue(EmailValue)
            query.addBindValue(OrganValue)
            query.addBindValue(OrdNumValue)

            query.exec()
            self.clientFIOLine.clear()
            self.clientOrdNumLine.clear()
            self.clientTelLine.clear()
            self.clientEmailLine.clear()
            self.clientOrganLine.clear()