from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
from PyQt5.QtSql import QSqlQuery

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 235)
        MainWindow.setMinimumSize(QtCore.QSize(500, 235))
        MainWindow.setMaximumSize(QtCore.QSize(500, 235))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 161, 18))
        self.label.setObjectName("label")
        self.executOrdNumLine = QtWidgets.QLineEdit(self.centralwidget)
        self.executOrdNumLine.setGeometry(QtCore.QRect(180, 60, 301, 24))
        self.executOrdNumLine.setObjectName("executOrdNumLine")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 211, 18))
        self.label_3.setObjectName("label_3")
        self.executLangLine = QtWidgets.QLineEdit(self.centralwidget)
        self.executLangLine.setGeometry(QtCore.QRect(180, 140, 301, 24))
        self.executLangLine.setObjectName("executLangLine")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 180, 271, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveExecutBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveExecutBtn.setObjectName("saveExecutBtn")
        self.horizontalLayout.addWidget(self.saveExecutBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancelExecutBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelExecutBtn.setObjectName("cancelExecutBtn")
        self.horizontalLayout.addWidget(self.cancelExecutBtn)
        self.executFIOLine = QtWidgets.QLineEdit(self.centralwidget)
        self.executFIOLine.setGeometry(QtCore.QRect(180, 20, 301, 24))
        self.executFIOLine.setObjectName("executFIOLine")
        self.ExecutPayLine = QtWidgets.QLineEdit(self.centralwidget)
        self.ExecutPayLine.setGeometry(QtCore.QRect(240, 100, 241, 24))
        self.ExecutPayLine.setObjectName("ExecutPayLine")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 121, 18))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 111, 18))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.executFIOLine, self.executOrdNumLine)
        MainWindow.setTabOrder(self.executOrdNumLine, self.ExecutPayLine)
        MainWindow.setTabOrder(self.ExecutPayLine, self.executLangLine)
        MainWindow.setTabOrder(self.executLangLine, self.saveExecutBtn)
        MainWindow.setTabOrder(self.saveExecutBtn, self.cancelExecutBtn)
        self.saveExecutBtn.clicked.connect(self.add_to_table)
        self.cancelExecutBtn.clicked.connect(MainWindow.close)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Добавить исполнителя"))
        self.label.setText(_translate("MainWindow", "ФИО Исполнителя"))
        self.label_3.setText(_translate("MainWindow", "Оплата за 1800 символов"))
        self.saveExecutBtn.setText(_translate("MainWindow", "Сохранить"))
        self.cancelExecutBtn.setText(_translate("MainWindow", "Отмена"))
        self.label_4.setText(_translate("MainWindow", "Языковая пара"))
        self.label_2.setText(_translate("MainWindow", "Номер заказа"))

    def add_to_table(self):
        con = QtSql.QSqlDatabase.addDatabase('QSQLITE')
        con.setDatabaseName('TAH.db')
        con.open()
        stm = QtSql.QSqlTableModel()
        stm.setTable('Executors')
        stm.setSort(1, QtCore.Qt.AscendingOrder)
        stm.select()
        query = QSqlQuery()
        FIOValue = self.executFIOLine.text()
        LangValue = self.executLangLine.text()
        PayValue = self.ExecutPayLine.text()
        OrdNumValue = self.executOrdNumLine.text()

        if FIOValue != "" and LangValue != "" and OrdNumValue != "" and PayValue != "":
            query.prepare("INSERT INTO Executors(Executor_name, Languages, Cost_for_1800s, Order_ID)"
                          "VALUES (?, ?, ?, ?)")
            query.addBindValue(FIOValue)
            query.addBindValue(LangValue)
            query.addBindValue(PayValue)
            query.addBindValue(OrdNumValue)
            query.exec()
            self.executFIOLine.clear()
            self.executLangLine.clear()
            self.ExecutPayLine.clear()
            self.executOrdNumLine.clear()