import sqlite3
import sys

from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
from PyQt5.QtSql import QSqlQuery
from PyQt5.QtWidgets import QListView


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(647, 354)
        MainWindow.setMinimumSize(QtCore.QSize(647, 354))
        MainWindow.setMaximumSize(QtCore.QSize(647, 354))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBoxOrder = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxOrder.setGeometry(QtCore.QRect(10, 10, 621, 281))
        self.groupBoxOrder.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.groupBoxOrder.setFont(font)
        self.groupBoxOrder.setStyleSheet("font: 9pt \"Arial\";")
        self.groupBoxOrder.setObjectName("groupBoxOrder")
        self.OrdNumLabel = QtWidgets.QLabel(self.groupBoxOrder)
        self.OrdNumLabel.setGeometry(QtCore.QRect(10, 30, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.OrdNumLabel.setFont(font)
        self.OrdNumLabel.setStyleSheet("")
        self.OrdNumLabel.setObjectName("OrdNumLabel")
        self.ordNumText = QtWidgets.QPlainTextEdit(self.groupBoxOrder)
        self.ordNumText.setGeometry(QtCore.QRect(90, 20, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ordNumText.setFont(font)
        self.ordNumText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ordNumText.setFrameShape(QtWidgets.QFrame.Box)
        self.ordNumText.setMidLineWidth(0)
        self.ordNumText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ordNumText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ordNumText.setPlainText("")
        self.ordNumText.setBackgroundVisible(False)
        self.ordNumText.setCenterOnScroll(False)
        self.ordNumText.setObjectName("ordNumText")
        self.labelDateOrder = QtWidgets.QLabel(self.groupBoxOrder)
        self.labelDateOrder.setGeometry(QtCore.QRect(10, 90, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelDateOrder.setFont(font)
        self.labelDateOrder.setObjectName("labelDateOrder")
        self.labelManager = QtWidgets.QLabel(self.groupBoxOrder)
        self.labelManager.setGeometry(QtCore.QRect(280, 30, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelManager.setFont(font)
        self.labelManager.setStyleSheet("font: 9pt \"Arial\";")
        self.labelManager.setObjectName("labelManager")
        self.acceptDate = QtWidgets.QDateEdit(self.groupBoxOrder)
        self.acceptDate.setGeometry(QtCore.QRect(140, 80, 131, 31))
        self.acceptDate.setObjectName("acceptDate")
        self.labelClient = QtWidgets.QLabel(self.groupBoxOrder)
        self.labelClient.setGeometry(QtCore.QRect(10, 140, 81, 18))
        self.labelClient.setObjectName("labelClient")
        self.labelExecutor = QtWidgets.QLabel(self.groupBoxOrder)
        self.labelExecutor.setGeometry(QtCore.QRect(290, 140, 121, 18))
        self.labelExecutor.setObjectName("labelExecutor")
        self.labelPassOrder = QtWidgets.QLabel(self.groupBoxOrder)
        self.labelPassOrder.setGeometry(QtCore.QRect(300, 90, 91, 18))
        self.labelPassOrder.setObjectName("labelPassOrder")
        self.passDate = QtWidgets.QDateEdit(self.groupBoxOrder)
        self.passDate.setGeometry(QtCore.QRect(400, 80, 131, 31))
        self.passDate.setObjectName("passDate")
        self.ManagerLine = QtWidgets.QLineEdit(self.groupBoxOrder)
        self.ManagerLine.setGeometry(QtCore.QRect(380, 30, 221, 24))
        self.ManagerLine.setObjectName("ManagerLine")
        self.labelLang = QtWidgets.QLabel(self.groupBoxOrder)
        self.labelLang.setGeometry(QtCore.QRect(10, 190, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelLang.setFont(font)
        self.labelLang.setObjectName("labelLang")
        self.LangLine = QtWidgets.QLineEdit(self.groupBoxOrder)
        self.LangLine.setGeometry(QtCore.QRect(140, 190, 131, 24))
        self.LangLine.setObjectName("LangLine")
        self.labelTax = QtWidgets.QLabel(self.groupBoxOrder)
        self.labelTax.setGeometry(QtCore.QRect(10, 240, 64, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTax.setFont(font)
        self.labelTax.setObjectName("labelTax")
        self.TaxLine = QtWidgets.QLineEdit(self.groupBoxOrder)
        self.TaxLine.setGeometry(QtCore.QRect(90, 240, 181, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TaxLine.setFont(font)
        self.TaxLine.setObjectName("TaxLine")
        self.labelSymb = QtWidgets.QLabel(self.groupBoxOrder)
        self.labelSymb.setGeometry(QtCore.QRect(290, 190, 151, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelSymb.setFont(font)
        self.labelSymb.setObjectName("labelSymb")
        self.SymbLine = QtWidgets.QLineEdit(self.groupBoxOrder)
        self.SymbLine.setGeometry(QtCore.QRect(440, 190, 161, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SymbLine.setFont(font)
        self.SymbLine.setObjectName("SymbLine")
        self.labelResult = QtWidgets.QLabel(self.groupBoxOrder)
        self.labelResult.setGeometry(QtCore.QRect(290, 240, 61, 21))
        self.labelResult.setObjectName("labelResult")
        self.comboClient = QtWidgets.QComboBox(self.groupBoxOrder)
        self.comboClient.setGeometry(QtCore.QRect(99, 140, 171, 24))
        self.comboClient.setObjectName("comboClient")
        self.comboExecut = QtWidgets.QComboBox(self.groupBoxOrder)
        self.comboExecut.setGeometry(QtCore.QRect(409, 140, 191, 24))
        self.comboExecut.setObjectName("comboExecut")
        self.ResultLine = QtWidgets.QLineEdit(self.groupBoxOrder)
        self.ResultLine.setGeometry(QtCore.QRect(380, 240, 221, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ResultLine.setFont(font)
        self.ResultLine.setObjectName("ResultLine")
        self.addOrderBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addOrderBtn.setGeometry(QtCore.QRect(10, 300, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.addOrderBtn.setFont(font)
        self.addOrderBtn.setObjectName("addOrderBtn")
        self.cancelOrderBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cancelOrderBtn.setGeometry(QtCore.QRect(510, 300, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cancelOrderBtn.setFont(font)
        self.cancelOrderBtn.setObjectName("cancelOrderBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.OrdNumLabel.setBuddy(self.ordNumText)
        self.labelTax.setBuddy(self.TaxLine)
        self.labelSymb.setBuddy(self.SymbLine)

        self.retranslateUi(MainWindow)
        self.cancelOrderBtn.clicked.connect(MainWindow.close)
        self.comboClient.activated.connect(self.ClientChoose)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.ordNumText, self.acceptDate)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBoxOrder.setTitle(_translate("MainWindow", "Заказ"))
        self.OrdNumLabel.setText(_translate("MainWindow", "Заказ № /"))
        self.labelDateOrder.setText(_translate("MainWindow", "Дата принятия"))
        self.labelManager.setText(_translate("MainWindow", "Менеджер"))
        self.labelClient.setText(_translate("MainWindow", "Клиент"))
        self.labelExecutor.setText(_translate("MainWindow", "Исполнитель"))
        self.labelPassOrder.setText(_translate("MainWindow", "Сдать до"))
        self.labelLang.setText(_translate("MainWindow", "Языковая пара"))
        self.labelTax.setText(_translate("MainWindow", "Тариф"))
        self.labelSymb.setText(_translate("MainWindow", "Кол-во символов"))
        self.labelResult.setText(_translate("MainWindow", "ИТОГО"))
        self.addOrderBtn.setText(_translate("MainWindow", "Сохранить "))
        self.cancelOrderBtn.setText(_translate("MainWindow", "Отмена"))

    def add_Order_to_table(self):
        con = QtSql.QSqlDatabase.addDatabase('QSQLITE')
        con.setDatabaseName('TAH.db')
        con.open()

        stm = QtSql.QSqlTableModel()
        stm.setTable('Orders_Info')
        stm.setSort(1, QtCore.Qt.AscendingOrder)
        stm.select()
        query = QSqlQuery()

        ManagerValue = self.ManagerLine.text()
        AcceptValue = self.acceptDate.date()
        OrdNumValue = self.ordNumText.toPlainText()
        PassValue = self.passDate.date()
        ExecValue = self.comboExecut.currentText()
        CustValue = self.comboClient.currentText()
        LangValue = self.LangLine.text()
        TaxValue = self.TaxLine.text()
        SymbValue = self.SymbLine.text()
        ResultValue = int(self.SymbLine.text()) / 1800 * int(self.TaxLine.text())
        Res = int(ResultValue)

        if OrdNumValue != "" and ManagerValue != "" and ExecValue != "" and CustValue != "":
            query.prepare(
                "INSERT INTO Orders_Info(Manager, Order_accept, Order_pass, Executor_ID, Cust_ID, Order_Num, Languages, Tax, Symbols, Results )"
                "VALUES (?, ?, ?, ?, ?, ?, ?, ? ,?, ?)")

            query.addBindValue(ManagerValue)
            query.addBindValue(AcceptValue)
            query.addBindValue(PassValue)
            query.addBindValue(ExecValue)
            query.addBindValue(CustValue)
            query.addBindValue(OrdNumValue)
            query.addBindValue(LangValue)
            query.addBindValue(TaxValue)
            query.addBindValue(SymbValue)
            query.addBindValue(Res)

            query.exec()
            self.ResultLine.setText(str(Res))

    def ClientChoose(self):
        # con = QtSql.QSqlDatabase.addDatabase('QSQLITE')
        # con.setDatabaseName('TAH.db')
        # con.open()

        con = sqlite3.connect('TAH.db')
        cur = con.cursor()
        get_Client_name = "SELECT Cust_name FROM Customers"
        cur.execute(get_Client_name)

        results = cur.fetchall()
        for i in len(results):
            self.comboClient.addItems(results[i])

        cur.close()

        # stm = QtSql.QSqlTableModel()
        # stm.setTable('Customers')
        # stm.setSort(1, QtCore.Qt.AscendingOrder)
        # stm.select()
        #
        # model = QtSql.QSqlQueryModel()
        #
        # entries = model.setQuery("""SELECT Cust_name FROM Customers""")
        #
        # self.comboClient.setModel(model)
        #
        # # for i in entries:
        # #     item = entries
        # #     self.comboClient.addItems(item)
