from PyQt5 import QtCore, QtGui, QtWidgets, QtSql
from PyQt5.QtSql import QSqlTableModel

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1182, 779)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.addOrderBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addOrderBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addOrderBtn.sizePolicy().hasHeightForWidth())
        self.addOrderBtn.setSizePolicy(sizePolicy)
        self.addOrderBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.addOrderBtn.setFont(font)
        self.addOrderBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.addOrderBtn.setIconSize(QtCore.QSize(60, 60))
        self.addOrderBtn.setShortcut("")
        self.addOrderBtn.setCheckable(False)
        self.addOrderBtn.setObjectName("addOrderBtn")
        self.horizontalLayout.addWidget(self.addOrderBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.addClientBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.addClientBtn.setFont(font)
        self.addClientBtn.setObjectName("addClientBtn")
        self.horizontalLayout.addWidget(self.addClientBtn)
        self.ClientsBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.ClientsBtn.setFont(font)
        self.ClientsBtn.setIconSize(QtCore.QSize(60, 60))
        self.ClientsBtn.setObjectName("ClientsBtn")
        self.horizontalLayout.addWidget(self.ClientsBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.addExecutBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.addExecutBtn.setFont(font)
        self.addExecutBtn.setObjectName("addExecutBtn")
        self.horizontalLayout.addWidget(self.addExecutBtn)
        self.ExecutBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.ExecutBtn.setFont(font)
        self.ExecutBtn.setIconSize(QtCore.QSize(60, 60))
        self.ExecutBtn.setObjectName("ExecutBtn")
        self.horizontalLayout.addWidget(self.ExecutBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.mainTable = QtWidgets.QTableView(self.centralwidget)
        self.mainTable.setObjectName("mainTable")
        self.verticalLayout.addWidget(self.mainTable)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.create_table()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TransAgencyHelper"))
        self.addOrderBtn.setText(_translate("MainWindow", "Новый заказ"))
        self.addClientBtn.setText(_translate("MainWindow", "Добавить клиента"))
        self.ClientsBtn.setText(_translate("MainWindow", "Список клиентов"))
        self.addExecutBtn.setText(_translate("MainWindow", "Добавить исполнителя"))
        self.ExecutBtn.setText(_translate("MainWindow", "Список исполнителей"))

    def create_table(self):
        con = QtSql.QSqlDatabase.addDatabase('QSQLITE')
        con.setDatabaseName('TAH.db')
        con.open()
        stm = QtSql.QSqlTableModel()
        stm.setTable('Orders_Info')
        stm.setEditStrategy(QSqlTableModel.OnFieldChange)
        stm.setSort(1, QtCore.Qt.AscendingOrder)
        stm.select()
        model = QtSql.QSqlQueryModel()
        model.setQuery("""SELECT Order_ID, Manager, Order_accept, Order_pass, Executor_ID, Cust_ID, Order_Num, 
                            Languages, Tax, Symbols, Results FROM Orders_Info""")
        model.setHeaderData(0, QtCore.Qt.Horizontal, '№/')
        model.setHeaderData(1, QtCore.Qt.Horizontal, 'Менеджер')
        model.setHeaderData(2, QtCore.Qt.Horizontal, 'Дата принятия заказа')
        model.setHeaderData(3, QtCore.Qt.Horizontal, 'Дата сдачи заказа')
        # model.setHeaderData(4, QtCore.Qt.Horizontal, 'Статус заказа')
        model.setHeaderData(4, QtCore.Qt.Horizontal, 'Исполнитель')
        model.setHeaderData(5, QtCore.Qt.Horizontal, 'Заказчик')
        model.setHeaderData(6, QtCore.Qt.Horizontal, 'Номер заказа')
        model.setHeaderData(7, QtCore.Qt.Horizontal, 'Языковая пара')
        model.setHeaderData(8, QtCore.Qt.Horizontal, 'Тариф')
        model.setHeaderData(9, QtCore.Qt.Horizontal, 'Кол-во символов')
        model.setHeaderData(10, QtCore.Qt.Horizontal, 'Итог')
        model.__sizeof__()
        model.resetInternalData()
        self.mainTable.setModel(model)